---
apiVersion: v1
kind: Namespace
metadata:
  name: cs-ns
  labels:
    app: cs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-cm
  namespace: cs-ns
  labels:
    app: cs
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-146.190.4.231.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: cs-secret
  namespace: cs-ns
  labels:
    app: cs
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=